import type { GuiaDestino } from './destinos.ts';

/**
 * Guías de los destinos internacionales más buscados desde Lima.
 * Clave: nombre normalizado (minúsculas, sin tildes) tal como lo envía Apps Script
 * (Config.gs → AEROPUERTOS_INTERNACIONALES).
 * "documento" es orientativo para viajeros peruanos: los requisitos cambian,
 * por eso la web siempre recomienda confirmarlos antes de comprar.
 */
const DNI_REGION = 'Peruanos: DNI vigente o pasaporte (acuerdos de la región).';
const SCHENGEN = 'Peruanos: pasaporte vigente; no se pide visa para turismo de hasta 90 días (espacio Schengen).';
const EEUU = 'Peruanos: pasaporte y visa de turista de EE. UU. vigente.';
const REVISAR = 'Pasaporte vigente. Revisa los requisitos de ingreso para peruanos antes de comprar.';

export const GUIAS_INTERNACIONALES: Record<string, GuiaDestino> = {
  'santiago de chile': {
    nombre: 'Santiago de Chile', region: 'Chile', lema: 'Cordillera, vino y ciudad a un vuelo corto',
    descripcion: 'Una capital moderna rodeada de la cordillera de los Andes: barrios con onda, cerros con vista panorámica y viñedos de clase mundial a menos de una hora. En invierno, centros de esquí a pocas horas.',
    mejorEpoca: 'Septiembre a noviembre y marzo a mayo (clima templado). De junio a agosto, temporada de esquí.',
    clima: 'Veranos calurosos y secos; inviernos fríos con alguna lluvia.',
    imperdibles: [
      { titulo: 'Cerro San Cristóbal', texto: 'Sube en funicular o teleférico para ver toda la ciudad con los Andes de fondo.' },
      { titulo: 'Barrio Lastarria y Bellavista', texto: 'Cafés, bares, librerías y La Chascona, una de las casas de Pablo Neruda.' },
      { titulo: 'Valle del Maipo o Casablanca', texto: 'Tours de viñedos con degustación a menos de una hora.' },
      { titulo: 'Valparaíso y Viña del Mar', texto: 'Cerros de colores y playa a unas 2 horas: ideal para un día.' },
    ],
    consejos: [
      'La tarjeta bip! sirve para el metro y los buses.',
      'Lleva una casaca: incluso en verano refresca por la noche.',
    ],
    desdeAeropuerto: 'Del aeropuerto Arturo Merino Benítez al centro hay unos 30 minutos en taxi o en bus Centropuerto/Turbus.',
    documento: DNI_REGION, moneda: 'Peso chileno (CLP)', idioma: 'Español',
    fotos: { busqueda: 'Santiago Chile Andes skyline', wikipedia: 'Santiago de Chile' },
  },
  'buenos aires': {
    nombre: 'Buenos Aires', region: 'Argentina', lema: 'Tango, parrilla y noches que no terminan',
    descripcion: 'Avenidas europeas, barrios con personalidad propia, librerías, teatros y la mejor carne del continente. Una ciudad para caminar de día y vivir de noche.',
    mejorEpoca: 'Marzo a mayo y septiembre a noviembre (primavera y otoño).',
    clima: 'Veranos calurosos y húmedos; inviernos frescos.',
    imperdibles: [
      { titulo: 'La Boca y Caminito', texto: 'Casas de colores, tango en la calle y la Bombonera.' },
      { titulo: 'San Telmo', texto: 'Feria de antigüedades los domingos y milongas.' },
      { titulo: 'Recoleta y Palermo', texto: 'El cementerio de la Recoleta, parques, cafés y restaurantes.' },
      { titulo: 'Una parrilla y un show de tango', texto: 'Bife de chorizo, vino Malbec y tango en vivo.' },
    ],
    consejos: [
      'Cambia dinero solo en lugares oficiales o paga con tarjeta; consulta antes el tipo de cambio.',
      'Se cena tarde: muchos restaurantes se llenan después de las 9 p. m.',
    ],
    desdeAeropuerto: 'Desde Ezeiza (EZE) al centro hay unos 45–60 minutos; desde Aeroparque (AEP), unos 15–20 minutos.',
    documento: DNI_REGION, moneda: 'Peso argentino (ARS)', idioma: 'Español',
    fotos: { busqueda: 'Buenos Aires Argentina', wikipedia: 'Buenos Aires' },
  },
  'sao paulo': {
    nombre: 'São Paulo', region: 'Brasil', lema: 'La gran metrópoli de Sudamérica',
    descripcion: 'Gastronomía de todo el mundo, museos, arte urbano y una vida nocturna enorme. Además, es un buen punto de partida hacia las playas del litoral paulista.',
    mejorEpoca: 'Abril a septiembre (menos lluvia y calor más suave).',
    clima: 'Templado; de diciembre a marzo hay calor y lluvias por la tarde.',
    imperdibles: [
      { titulo: 'Avenida Paulista y el MASP', texto: 'El corazón de la ciudad y uno de los museos de arte más importantes de Latinoamérica.' },
      { titulo: 'Beco do Batman', texto: 'Callejones llenos de grafitis en Vila Madalena.' },
      { titulo: 'Mercado Municipal', texto: 'Famoso por el sándwich de mortadela y las frutas tropicales.' },
      { titulo: 'Parque Ibirapuera', texto: 'Museos, lagos y arquitectura de Oscar Niemeyer.' },
    ],
    consejos: [
      'El metro es la forma más rápida de moverse: el tráfico es intenso.',
      'Aprende algunas frases básicas en portugués; se agradece mucho.',
    ],
    desdeAeropuerto: 'Desde Guarulhos (GRU) al centro hay entre 45 y 90 minutos según el tráfico; también hay tren y buses al aeropuerto.',
    documento: DNI_REGION, moneda: 'Real brasileño (BRL)', idioma: 'Portugués',
    fotos: { busqueda: 'Sao Paulo Brazil skyline', wikipedia: 'São Paulo' },
  },
  'rio de janeiro': {
    nombre: 'Río de Janeiro', region: 'Brasil', lema: 'Playas, samba y paisajes de postal',
    descripcion: 'Montañas que caen al mar, playas legendarias y una energía contagiosa. Pocas ciudades del mundo tienen una geografía tan espectacular.',
    mejorEpoca: 'Mayo a octubre (menos calor y menos lluvia). En febrero o marzo, el Carnaval.',
    clima: 'Tropical: caluroso casi todo el año, con lluvias en verano.',
    imperdibles: [
      { titulo: 'Cristo Redentor', texto: 'Sube al Corcovado para la vista más famosa de Río.' },
      { titulo: 'Pan de Azúcar', texto: 'Teleférico al atardecer sobre la bahía de Guanabara.' },
      { titulo: 'Copacabana e Ipanema', texto: 'Playa, caipiriñas y el atardecer en el Arpoador.' },
      { titulo: 'Escadaria Selarón y Santa Teresa', texto: 'Escalera de azulejos y un barrio bohemio en las alturas.' },
    ],
    consejos: [
      'Lleva lo justo a la playa y no exhibas el celular en zonas concurridas.',
      'Compra las entradas al Cristo y al Pan de Azúcar en línea para evitar colas.',
    ],
    desdeAeropuerto: 'Desde Galeão (GIG) a Copacabana hay unos 40–60 minutos según el tráfico.',
    documento: DNI_REGION, moneda: 'Real brasileño (BRL)', idioma: 'Portugués',
    fotos: { busqueda: 'Rio de Janeiro Sugarloaf', wikipedia: 'Río de Janeiro' },
  },
  florianopolis: {
    nombre: 'Florianópolis', region: 'Brasil', lema: 'La isla de las 40 playas',
    descripcion: 'Una isla con playas para todos los gustos: olas para surf, bahías tranquilas, lagunas y dunas. Naturaleza y buena comida de mar.',
    mejorEpoca: 'Diciembre a marzo para playa; abril y noviembre con menos gente.',
    clima: 'Veranos cálidos; inviernos frescos.',
    imperdibles: [
      { titulo: 'Lagoa da Conceição', texto: 'Laguna con deportes de agua, dunas para sandboard y restaurantes.' },
      { titulo: 'Praia Mole y Joaquina', texto: 'Playas de surf con mucho ambiente.' },
      { titulo: 'Ribeirão da Ilha', texto: 'Pueblo colonial famoso por sus ostras.' },
    ],
    consejos: ['Alquilar un auto ayuda a recorrer las playas del norte y del sur.'],
    desdeAeropuerto: 'El aeropuerto Hercílio Luz está a unos 20–30 minutos del centro y de muchas playas.',
    documento: DNI_REGION, moneda: 'Real brasileño (BRL)', idioma: 'Portugués',
    fotos: { busqueda: 'Florianopolis beach', wikipedia: 'Florianópolis' },
  },
  bogota: {
    nombre: 'Bogotá', region: 'Colombia', lema: 'Arte, café y montaña',
    descripcion: 'Una capital vibrante en lo alto de los Andes: museos de primer nivel, grafiti, gastronomía y cerros con vista a toda la sabana.',
    mejorEpoca: 'Diciembre a marzo y julio a agosto (temporadas más secas).',
    clima: 'Fresco todo el año, con días que cambian de sol a lluvia.',
    altura: '2,640 m s. n. m.',
    imperdibles: [
      { titulo: 'La Candelaria', texto: 'El centro histórico, con casas coloniales y arte urbano.' },
      { titulo: 'Museo del Oro', texto: 'Una de las colecciones de orfebrería prehispánica más grandes del mundo.' },
      { titulo: 'Cerro de Monserrate', texto: 'Teleférico o funicular a 3,152 m con la ciudad a tus pies.' },
      { titulo: 'Usaquén', texto: 'Mercado de pulgas los domingos y restaurantes.' },
    ],
    consejos: ['Lleva una casaca y un paraguas: el clima cambia rápido.', 'Prueba el ajiaco santafereño.'],
    desdeAeropuerto: 'Desde El Dorado al centro hay unos 30–45 minutos en taxi.',
    documento: DNI_REGION, moneda: 'Peso colombiano (COP)', idioma: 'Español',
    fotos: { busqueda: 'Bogota Colombia Monserrate', wikipedia: 'Bogotá' },
  },
  medellin: {
    nombre: 'Medellín', region: 'Colombia', lema: 'La ciudad de la eterna primavera',
    descripcion: 'Clima perfecto, gente cálida y una transformación urbana admirada en el mundo. Montañas verdes, cafetales y pueblos de colores cerca.',
    mejorEpoca: 'Todo el año. En agosto, la Feria de las Flores.',
    clima: 'Templado y agradable todo el año.',
    imperdibles: [
      { titulo: 'Comuna 13', texto: 'Grafiti, escaleras eléctricas e historias de transformación.' },
      { titulo: 'Metrocable', texto: 'Teleféricos que conectan los barrios altos, con vistas increíbles.' },
      { titulo: 'Guatapé y El Peñol', texto: 'Una piedra gigante de 700 escalones y un pueblo de colores a unas 2 horas.' },
      { titulo: 'Plaza Botero', texto: 'Esculturas de Fernando Botero en el centro.' },
    ],
    consejos: ['El metro es limpio, seguro y económico.', 'Prueba la bandeja paisa.'],
    desdeAeropuerto: 'El aeropuerto José María Córdova está en Rionegro, a unos 45–60 minutos de la ciudad.',
    documento: DNI_REGION, moneda: 'Peso colombiano (COP)', idioma: 'Español',
    fotos: { busqueda: 'Medellin Colombia', wikipedia: 'Medellín' },
  },
  cartagena: {
    nombre: 'Cartagena', region: 'Colombia', lema: 'Murallas, Caribe y atardeceres',
    descripcion: 'Una ciudad amurallada de calles de colores, balcones con flores y el mar Caribe al frente. Desde aquí salen paseos a islas de agua turquesa.',
    mejorEpoca: 'Diciembre a abril (temporada seca).',
    clima: 'Caluroso y húmedo todo el año.',
    imperdibles: [
      { titulo: 'Ciudad amurallada', texto: 'Recorre sus plazas de día y su ambiente de noche.' },
      { titulo: 'Getsemaní', texto: 'Barrio de arte urbano, música y bares.' },
      { titulo: 'Islas del Rosario y Barú', texto: 'Playas de arena blanca y agua turquesa en lancha.' },
      { titulo: 'Castillo San Felipe', texto: 'La fortaleza española más grande de América.' },
    ],
    consejos: ['Lleva bloqueador, sombrero y mucha agua.', 'Acuerda el precio de los paseos en lancha antes de subir.'],
    desdeAeropuerto: 'El aeropuerto Rafael Núñez está a unos 10–15 minutos de la ciudad amurallada.',
    documento: DNI_REGION, moneda: 'Peso colombiano (COP)', idioma: 'Español',
    fotos: { busqueda: 'Cartagena Colombia old town', wikipedia: 'Cartagena de Indias' },
  },
  quito: {
    nombre: 'Quito', region: 'Ecuador', lema: 'En la mitad del mundo',
    descripcion: 'Uno de los centros históricos mejor conservados de América, rodeado de volcanes. Cruza la línea ecuatorial y sube a más de 4,000 metros en teleférico.',
    mejorEpoca: 'Junio a septiembre (temporada seca).',
    clima: 'Primaveral de día y fresco de noche; lluvias por la tarde en temporada húmeda.',
    altura: '2,850 m s. n. m.',
    imperdibles: [
      { titulo: 'Centro histórico', texto: 'Iglesias barrocas como La Compañía y la Basílica del Voto Nacional.' },
      { titulo: 'Mitad del Mundo', texto: 'El monumento en la línea ecuatorial.' },
      { titulo: 'TelefériQo', texto: 'Sube al volcán Pichincha para una vista enorme.' },
      { titulo: 'Mercado de Otavalo', texto: 'Uno de los mercados artesanales más famosos de Sudamérica, a unas 2 horas.' },
    ],
    consejos: ['Ecuador usa el dólar: lleva billetes pequeños.', 'Tómate el primer día con calma por la altura.'],
    desdeAeropuerto: 'El aeropuerto Mariscal Sucre está en Tababela, a unos 45–60 minutos de la ciudad.',
    documento: DNI_REGION, moneda: 'Dólar estadounidense (USD)', idioma: 'Español',
    fotos: { busqueda: 'Quito Ecuador old town', wikipedia: 'Quito' },
  },
  'la paz': {
    nombre: 'La Paz', region: 'Bolivia', lema: 'La ciudad entre montañas',
    descripcion: 'Una ciudad única en un cañón andino, con el Illimani nevado de fondo y teleféricos como transporte público. Cerca están el lago Titicaca y el valle de la Luna.',
    mejorEpoca: 'Mayo a octubre (seco y soleado).',
    clima: 'Fresco de día y frío de noche.',
    altura: 'Aprox. 3,600 m s. n. m. (el aeropuerto, a más de 4,000 m)',
    imperdibles: [
      { titulo: 'Mi Teleférico', texto: 'La red de teleféricos urbanos más grande del mundo.' },
      { titulo: 'Valle de la Luna', texto: 'Formaciones de arcilla a minutos de la ciudad.' },
      { titulo: 'Mercado de las Brujas', texto: 'Un mercado de amuletos y tradiciones andinas.' },
      { titulo: 'Salar de Uyuni', texto: 'Desde La Paz salen vuelos y buses al salar más grande del mundo.' },
    ],
    consejos: ['Descansa al llegar y toma mate de coca.', 'Lleva ropa de abrigo.'],
    desdeAeropuerto: 'El aeropuerto de El Alto está a unos 30 minutos del centro de La Paz.',
    documento: DNI_REGION, moneda: 'Boliviano (BOB)', idioma: 'Español',
    fotos: { busqueda: 'La Paz Bolivia Illimani', wikipedia: 'La Paz' },
  },
  montevideo: {
    nombre: 'Montevideo', region: 'Uruguay', lema: 'Rambla, calma y buen asado',
    descripcion: 'Una capital tranquila frente al Río de la Plata, con una rambla de más de 20 km, barrios históricos y una cultura de mate y asado muy propia.',
    mejorEpoca: 'Diciembre a marzo (verano); octubre y noviembre son muy agradables.',
    clima: 'Templado, con veranos cálidos e inviernos fríos y ventosos.',
    imperdibles: [
      { titulo: 'Ciudad Vieja', texto: 'Plaza Independencia, el Teatro Solís y el Mercado del Puerto.' },
      { titulo: 'La Rambla', texto: 'Ideal para caminar o pedalear al atardecer.' },
      { titulo: 'Colonia del Sacramento', texto: 'Pueblo colonial Patrimonio de la Humanidad, a unas 2 horas.' },
      { titulo: 'Punta del Este', texto: 'El balneario más famoso de Sudamérica, a unas 2 horas.' },
    ],
    consejos: ['Prueba el chivito y un asado en el Mercado del Puerto.'],
    desdeAeropuerto: 'El aeropuerto de Carrasco está a unos 30 minutos del centro.',
    documento: DNI_REGION, moneda: 'Peso uruguayo (UYU)', idioma: 'Español',
    fotos: { busqueda: 'Montevideo Uruguay', wikipedia: 'Montevideo' },
  },
  mendoza: {
    nombre: 'Mendoza', region: 'Argentina', lema: 'Tierra del Malbec y del Aconcagua',
    descripcion: 'Viñedos al pie de la cordillera, bodegas para recorrer en bici y la montaña más alta de América a pocas horas.',
    mejorEpoca: 'Marzo y abril (vendimia) y de octubre a noviembre.',
    clima: 'Seco y soleado; veranos calurosos e inviernos fríos.',
    imperdibles: [
      { titulo: 'Bodegas de Luján de Cuyo y Valle de Uco', texto: 'Degustaciones y almuerzos entre viñedos.' },
      { titulo: 'Parque Provincial Aconcagua', texto: 'Mirador de la cumbre más alta de América.' },
      { titulo: 'Parque General San Martín', texto: 'Un enorme parque urbano con lagos y el Cerro de la Gloria.' },
    ],
    consejos: ['Reserva las bodegas con anticipación.'],
    desdeAeropuerto: 'El aeropuerto El Plumerillo está a unos 20 minutos del centro.',
    documento: DNI_REGION, moneda: 'Peso argentino (ARS)', idioma: 'Español',
    fotos: { busqueda: 'Mendoza vineyards Andes', wikipedia: 'Mendoza' },
  },
  panama: {
    nombre: 'Panamá', region: 'Panamá', lema: 'Canal, rascacielos y Caribe',
    descripcion: 'Una ciudad de rascacielos frente al Pacífico, un casco antiguo restaurado y el famoso canal. A poca distancia, islas caribeñas como San Blas.',
    mejorEpoca: 'Diciembre a abril (temporada seca).',
    clima: 'Tropical, caluroso y húmedo todo el año.',
    imperdibles: [
      { titulo: 'Canal de Panamá', texto: 'Mira cruzar los barcos desde las esclusas de Miraflores.' },
      { titulo: 'Casco Viejo', texto: 'Plazas, iglesias y terrazas con vista a la ciudad.' },
      { titulo: 'Cinta Costera', texto: 'Paseo frente al mar ideal al atardecer.' },
      { titulo: 'San Blas (Guna Yala)', texto: 'Islas paradisíacas del Caribe; se visitan en tour de uno o más días.' },
    ],
    consejos: ['Panamá usa el dólar estadounidense.', 'Lleva ropa ligera y un paraguas.'],
    desdeAeropuerto: 'Desde Tocumen a la ciudad hay unos 30–45 minutos.',
    documento: REVISAR, moneda: 'Balboa y dólar estadounidense (USD)', idioma: 'Español',
    fotos: { busqueda: 'Panama City skyline', wikipedia: 'Ciudad de Panamá' },
  },
  cancun: {
    nombre: 'Cancún', region: 'México', lema: 'El Caribe mexicano',
    descripcion: 'Playas de arena blanca, mar turquesa, cenotes y ruinas mayas. Base perfecta para recorrer la Riviera Maya.',
    mejorEpoca: 'Diciembre a abril (seco y soleado).',
    clima: 'Caluroso todo el año; de junio a noviembre es temporada de lluvias y huracanes.',
    imperdibles: [
      { titulo: 'Isla Mujeres', texto: 'Ferry a una isla de aguas tranquilas y playa Norte.' },
      { titulo: 'Chichén Itzá', texto: 'Una de las nuevas siete maravillas del mundo.' },
      { titulo: 'Cenotes', texto: 'Pozos de agua cristalina para nadar o bucear.' },
      { titulo: 'Tulum y Playa del Carmen', texto: 'Ruinas frente al mar y la Quinta Avenida.' },
    ],
    consejos: ['Usa bloqueador biodegradable en cenotes y arrecifes.', 'Si viajas entre junio y noviembre, contrata un seguro de viaje.'],
    desdeAeropuerto: 'El aeropuerto está a unos 20 minutos de la zona hotelera.',
    documento: REVISAR, moneda: 'Peso mexicano (MXN)', idioma: 'Español',
    fotos: { busqueda: 'Cancun beach Caribbean', wikipedia: 'Cancún' },
  },
  'ciudad de mexico': {
    nombre: 'Ciudad de México', region: 'México', lema: 'Historia, arte y la mejor comida callejera',
    descripcion: 'Una megaciudad con pirámides, museos de primer nivel, barrios llenos de vida y una gastronomía que es Patrimonio de la Humanidad.',
    mejorEpoca: 'Octubre a mayo (temporada seca).',
    clima: 'Templado; de junio a septiembre llueve casi todas las tardes.',
    altura: '2,240 m s. n. m.',
    imperdibles: [
      { titulo: 'Centro Histórico y Zócalo', texto: 'La Catedral, el Templo Mayor y el Palacio de Bellas Artes.' },
      { titulo: 'Teotihuacán', texto: 'Sube a las pirámides del Sol y de la Luna, a 1 hora.' },
      { titulo: 'Coyoacán y la Casa Azul', texto: 'El barrio y el museo de Frida Kahlo.' },
      { titulo: 'Roma y Condesa', texto: 'Parques, cafés y tacos al pastor.' },
    ],
    consejos: ['Compra con anticipación la entrada al Museo Frida Kahlo.', 'Muévete en metro o en taxis de aplicación.'],
    desdeAeropuerto: 'Desde el aeropuerto Benito Juárez (MEX) al centro hay unos 30–45 minutos.',
    documento: REVISAR, moneda: 'Peso mexicano (MXN)', idioma: 'Español',
    fotos: { busqueda: 'Mexico City Palacio de Bellas Artes', wikipedia: 'Ciudad de México' },
  },
  'punta cana': {
    nombre: 'Punta Cana', region: 'República Dominicana', lema: 'Playas de postal y todo incluido',
    descripcion: 'Kilómetros de arena blanca, palmeras y mar turquesa. El destino ideal para desconectarte en un resort frente al Caribe.',
    mejorEpoca: 'Diciembre a abril.',
    clima: 'Caluroso todo el año; de junio a noviembre puede haber huracanes.',
    imperdibles: [
      { titulo: 'Playa Bávaro', texto: 'Una de las playas más famosas del Caribe.' },
      { titulo: 'Isla Saona', texto: 'Excursión en catamarán a playas vírgenes y piscinas naturales.' },
      { titulo: 'Hoyo Azul', texto: 'Un cenote de agua turquesa en Cap Cana.' },
    ],
    consejos: ['Compara resorts "todo incluido": a veces sale más barato que pagar comidas aparte.'],
    desdeAeropuerto: 'El aeropuerto de Punta Cana está a unos 20–40 minutos de la mayoría de los resorts.',
    documento: REVISAR, moneda: 'Peso dominicano (DOP); el dólar se acepta mucho', idioma: 'Español',
    fotos: { busqueda: 'Punta Cana beach', wikipedia: 'Punta Cana' },
  },
  'la habana': {
    nombre: 'La Habana', region: 'Cuba', lema: 'Autos clásicos, música y Malecón',
    descripcion: 'Una ciudad detenida en el tiempo: fachadas coloniales, autos de los años 50, son cubano en cada esquina y el Malecón al atardecer.',
    mejorEpoca: 'Noviembre a abril.',
    clima: 'Caluroso; de junio a noviembre es temporada de lluvias y huracanes.',
    imperdibles: [
      { titulo: 'Habana Vieja', texto: 'Plaza de la Catedral, Plaza de Armas y calle Obispo.' },
      { titulo: 'El Malecón', texto: 'El paseo frente al mar más famoso de la isla.' },
      { titulo: 'Paseo en auto clásico', texto: 'Recorre la ciudad en un convertible de los años 50.' },
      { titulo: 'Viñales', texto: 'Valle de tabaco y mogotes, a unas 3 horas.' },
    ],
    consejos: ['Lleva efectivo: no siempre funcionan las tarjetas extranjeras.', 'Descarga mapas sin conexión: internet es limitado.'],
    desdeAeropuerto: 'El aeropuerto José Martí está a unos 30 minutos de La Habana Vieja.',
    documento: 'Pasaporte vigente y tarjeta de turista; confirma los requisitos vigentes antes de comprar.',
    moneda: 'Peso cubano (CUP)', idioma: 'Español',
    fotos: { busqueda: 'Havana Cuba classic car', wikipedia: 'La Habana' },
  },
  'san jose': {
    nombre: 'San José', region: 'Costa Rica', lema: 'Pura vida entre volcanes y bosques',
    descripcion: 'La puerta de entrada a Costa Rica: volcanes, bosques nubosos, playas en dos océanos y una biodiversidad impresionante.',
    mejorEpoca: 'Diciembre a abril (temporada seca).',
    clima: 'Templado en el valle central; cálido en las costas.',
    imperdibles: [
      { titulo: 'Volcán Arenal', texto: 'Aguas termales, puentes colgantes y cataratas.' },
      { titulo: 'Monteverde', texto: 'Bosque nuboso con tirolesas y avistamiento de quetzales.' },
      { titulo: 'Manuel Antonio', texto: 'Parque nacional con playas y monos.' },
    ],
    consejos: ['Alquilar un auto es la mejor forma de recorrer el país.'],
    desdeAeropuerto: 'El aeropuerto Juan Santamaría está en Alajuela, a unos 30 minutos de San José.',
    documento: REVISAR, moneda: 'Colón costarricense (CRC)', idioma: 'Español',
    fotos: { busqueda: 'Costa Rica Arenal volcano', wikipedia: 'Costa Rica' },
  },
  miami: {
    nombre: 'Miami', region: 'Estados Unidos', lema: 'Playa, compras y ambiente latino',
    descripcion: 'Playas de arena blanca, edificios art déco, compras para todos los presupuestos y un ambiente latino donde te entienden en español.',
    mejorEpoca: 'Noviembre a abril (seco y templado).',
    clima: 'Tropical; de junio a noviembre hace mucho calor y es temporada de huracanes.',
    imperdibles: [
      { titulo: 'South Beach y Ocean Drive', texto: 'Playa, art déco y vida nocturna.' },
      { titulo: 'Wynwood Walls', texto: 'Uno de los museos de arte urbano al aire libre más famosos.' },
      { titulo: 'Pequeña Habana', texto: 'Café cubano, dominó y la Calle Ocho.' },
      { titulo: 'Outlets y centros comerciales', texto: 'Dolphin Mall, Sawgrass Mills y Aventura.' },
    ],
    consejos: ['Contrata un seguro médico de viaje: la atención en EE. UU. es muy cara.', 'Alquila auto si piensas ir a outlets o a los Cayos.'],
    desdeAeropuerto: 'Del aeropuerto de Miami a South Beach hay unos 25–35 minutos.',
    documento: EEUU, moneda: 'Dólar estadounidense (USD)', idioma: 'Inglés y español',
    fotos: { busqueda: 'Miami Beach Ocean Drive', wikipedia: 'Miami' },
  },
  orlando: {
    nombre: 'Orlando', region: 'Estados Unidos', lema: 'La capital mundial de los parques temáticos',
    descripcion: 'Disney, Universal y muchos parques más: diversión para niños y adultos, más outlets para hacer compras.',
    mejorEpoca: 'De enero a mayo y de septiembre a noviembre, evitando feriados de EE. UU.',
    clima: 'Caluroso y húmedo en verano; templado en invierno.',
    imperdibles: [
      { titulo: 'Walt Disney World', texto: 'Magic Kingdom, EPCOT, Hollywood Studios y Animal Kingdom.' },
      { titulo: 'Universal Orlando', texto: 'El mundo de Harry Potter y atracciones de película.' },
      { titulo: 'Kennedy Space Center', texto: 'Cohetes reales y la historia de la NASA, a 1 hora.' },
      { titulo: 'Outlets', texto: 'Orlando Vineland y International Drive.' },
    ],
    consejos: ['Compra las entradas a los parques en línea y con anticipación.', 'Alquilar auto es casi indispensable.'],
    desdeAeropuerto: 'El aeropuerto de Orlando (MCO) está a unos 20–30 minutos de la zona de parques.',
    documento: EEUU, moneda: 'Dólar estadounidense (USD)', idioma: 'Inglés',
    fotos: { busqueda: 'Orlando Florida', wikipedia: 'Orlando (Florida)' },
  },
  'nueva york': {
    nombre: 'Nueva York', region: 'Estados Unidos', lema: 'La ciudad que nunca duerme',
    descripcion: 'Rascacielos, Broadway, museos legendarios y barrios donde cabe el mundo entero. Una ciudad que se recorre a pie y en metro.',
    mejorEpoca: 'Abril a junio y septiembre a noviembre. En diciembre, las luces navideñas.',
    clima: 'Veranos calurosos e inviernos fríos con nieve.',
    imperdibles: [
      { titulo: 'Central Park', texto: 'Caminatas, bicicleta y lagos en el corazón de Manhattan.' },
      { titulo: 'Times Square y Broadway', texto: 'Luces de neón y musicales de primer nivel.' },
      { titulo: 'Estatua de la Libertad', texto: 'Ferry desde Battery Park; el ferry de Staten Island es gratis y pasa cerca.' },
      { titulo: 'Puente de Brooklyn', texto: 'Crúzalo a pie al atardecer con vista a Manhattan.' },
    ],
    consejos: ['El metro funciona las 24 horas: usa tu tarjeta sin contacto.', 'Contrata un seguro médico de viaje.'],
    desdeAeropuerto: 'Desde JFK a Manhattan hay aprox. 1 hora en AirTrain + metro, o en taxi.',
    documento: EEUU, moneda: 'Dólar estadounidense (USD)', idioma: 'Inglés',
    fotos: { busqueda: 'New York City Manhattan skyline', wikipedia: 'Nueva York' },
  },
  'los angeles': {
    nombre: 'Los Ángeles', region: 'Estados Unidos', lema: 'Cine, playas y sol de California',
    descripcion: 'Hollywood, playas míticas, parques temáticos y carreteras junto al Pacífico. El sueño californiano en una sola ciudad.',
    mejorEpoca: 'Marzo a mayo y septiembre a noviembre.',
    clima: 'Soleado y seco casi todo el año.',
    imperdibles: [
      { titulo: 'Hollywood', texto: 'El Paseo de la Fama y el mirador del letrero.' },
      { titulo: 'Santa Mónica y Venice', texto: 'Muelle, playa y paseo de patinadores.' },
      { titulo: 'Universal Studios', texto: 'Recorre sets de cine reales.' },
      { titulo: 'Griffith Observatory', texto: 'Vista de toda la ciudad al atardecer.' },
    ],
    consejos: ['La ciudad es enorme: alquila un auto o agrupa tus visitas por zona.'],
    desdeAeropuerto: 'Desde LAX a Hollywood o Santa Mónica hay entre 30 y 60 minutos según el tráfico.',
    documento: EEUU, moneda: 'Dólar estadounidense (USD)', idioma: 'Inglés',
    fotos: { busqueda: 'Los Angeles Hollywood sign', wikipedia: 'Los Ángeles' },
  },
  madrid: {
    nombre: 'Madrid', region: 'España', lema: 'Museos, tapas y vida en la calle',
    descripcion: 'Una capital alegre y abierta: museos de clase mundial, plazas llenas de terrazas, tapas a toda hora y una noche que empieza tarde.',
    mejorEpoca: 'Abril a junio y septiembre a octubre.',
    clima: 'Veranos muy calurosos e inviernos fríos y secos.',
    imperdibles: [
      { titulo: 'Museo del Prado', texto: 'Velázquez, Goya y El Bosco en una de las mejores pinacotecas del mundo.' },
      { titulo: 'Parque del Retiro', texto: 'El estanque, el Palacio de Cristal y largos paseos.' },
      { titulo: 'Plaza Mayor y La Latina', texto: 'Bocadillo de calamares y ruta de tapas.' },
      { titulo: 'Toledo o Segovia', texto: 'Ciudades históricas a menos de 1 hora en tren.' },
    ],
    consejos: ['El metro es rápido y económico.', 'Muchos museos tienen horas de entrada gratuita: revísalas.'],
    desdeAeropuerto: 'Desde Barajas al centro hay unos 30–40 minutos en metro (línea 8) o en tren de Cercanías.',
    documento: SCHENGEN, moneda: 'Euro (EUR)', idioma: 'Español',
    fotos: { busqueda: 'Madrid Spain Gran Via', wikipedia: 'Madrid' },
  },
  barcelona: {
    nombre: 'Barcelona', region: 'España', lema: 'Gaudí, mar y Mediterráneo',
    descripcion: 'Arquitectura modernista única, playas urbanas, barrios góticos y una gastronomía de primer nivel junto al Mediterráneo.',
    mejorEpoca: 'Mayo, junio y septiembre.',
    clima: 'Mediterráneo: veranos calurosos e inviernos suaves.',
    imperdibles: [
      { titulo: 'Sagrada Familia', texto: 'La obra maestra de Gaudí. Compra la entrada en línea.' },
      { titulo: 'Park Güell', texto: 'Mosaicos de colores y vista de la ciudad.' },
      { titulo: 'Barrio Gótico y El Born', texto: 'Callejuelas medievales, plazas y bares.' },
      { titulo: 'La Barceloneta', texto: 'Playa y paella frente al mar.' },
    ],
    consejos: ['Cuida tus pertenencias en Las Ramblas y en el metro.', 'Reserva Sagrada Familia y Park Güell con días de anticipación.'],
    desdeAeropuerto: 'Desde El Prat a la Plaça Catalunya hay unos 35 minutos en Aerobús.',
    documento: SCHENGEN, moneda: 'Euro (EUR)', idioma: 'Español y catalán',
    fotos: { busqueda: 'Barcelona Sagrada Familia', wikipedia: 'Barcelona' },
  },
  paris: {
    nombre: 'París', region: 'Francia', lema: 'La ciudad de la luz',
    descripcion: 'La Torre Eiffel, el Louvre, cafés en cada esquina y paseos a orillas del Sena. Un clásico que siempre sorprende.',
    mejorEpoca: 'Abril a junio y septiembre a octubre.',
    clima: 'Templado; inviernos fríos y veranos agradables.',
    imperdibles: [
      { titulo: 'Torre Eiffel', texto: 'Sube al atardecer o mírala iluminada desde el Trocadéro.' },
      { titulo: 'Museo del Louvre', texto: 'La Mona Lisa y miles de obras maestras. Reserva tu hora.' },
      { titulo: 'Montmartre', texto: 'El Sacré-Cœur, pintores y vistas de la ciudad.' },
      { titulo: 'Crucero por el Sena', texto: 'Ve los monumentos desde el río.' },
    ],
    consejos: ['Compra en línea las entradas al Louvre y a la Torre Eiffel.', 'El metro llega a casi todos lados.'],
    desdeAeropuerto: 'Desde Charles de Gaulle al centro hay unos 35–50 minutos en tren RER B.',
    documento: SCHENGEN, moneda: 'Euro (EUR)', idioma: 'Francés',
    fotos: { busqueda: 'Paris Eiffel Tower', wikipedia: 'París' },
  },
  londres: {
    nombre: 'Londres', region: 'Reino Unido', lema: 'Historia real y cultura moderna',
    descripcion: 'Palacios, museos gratuitos, mercados y musicales. Una ciudad donde la historia y lo moderno conviven en cada barrio.',
    mejorEpoca: 'Mayo a septiembre.',
    clima: 'Templado y cambiante; puede llover en cualquier momento.',
    imperdibles: [
      { titulo: 'Big Ben y el London Eye', texto: 'El Támesis y Westminster en un solo paseo.' },
      { titulo: 'Museo Británico', texto: 'Gratis, con piezas de todo el mundo.' },
      { titulo: 'Torre de Londres', texto: 'Las joyas de la Corona y 1,000 años de historia.' },
      { titulo: 'Camden y Borough Market', texto: 'Mercados con comida de todo el mundo.' },
    ],
    consejos: ['Paga el metro con tu tarjeta sin contacto.', 'Lleva siempre un paraguas pequeño.'],
    desdeAeropuerto: 'Desde Heathrow al centro hay de 15 a 45 minutos en Heathrow Express o en la Elizabeth line.',
    documento: 'Pasaporte vigente. Revisa si necesitas autorización electrónica (ETA) o visa antes de comprar.',
    moneda: 'Libra esterlina (GBP)', idioma: 'Inglés',
    fotos: { busqueda: 'London Big Ben Thames', wikipedia: 'Londres' },
  },
  roma: {
    nombre: 'Roma', region: 'Italia', lema: 'La ciudad eterna',
    descripcion: 'Un museo al aire libre: el Coliseo, el Vaticano, fuentes barrocas y la mejor pasta y helado en cada esquina.',
    mejorEpoca: 'Abril a junio y septiembre a octubre.',
    clima: 'Mediterráneo: veranos calurosos e inviernos suaves.',
    imperdibles: [
      { titulo: 'Coliseo y Foro Romano', texto: 'El corazón de la antigua Roma. Reserva la entrada.' },
      { titulo: 'Vaticano', texto: 'La Basílica de San Pedro y la Capilla Sixtina.' },
      { titulo: 'Fontana di Trevi', texto: 'Lanza una moneda para volver a Roma.' },
      { titulo: 'Trastevere', texto: 'Callejuelas, trattorias y ambiente nocturno.' },
    ],
    consejos: ['Compra en línea las entradas al Coliseo y a los Museos Vaticanos.', 'Lleva hombros y rodillas cubiertos para entrar a las iglesias.'],
    desdeAeropuerto: 'Desde Fiumicino a la estación Termini hay 32 minutos en el tren Leonardo Express.',
    documento: SCHENGEN, moneda: 'Euro (EUR)', idioma: 'Italiano',
    fotos: { busqueda: 'Rome Colosseum', wikipedia: 'Roma' },
  },
  lisboa: {
    nombre: 'Lisboa', region: 'Portugal', lema: 'Siete colinas frente al Atlántico',
    descripcion: 'Tranvías amarillos, miradores, azulejos y pastéis de nata. Una de las capitales más encantadoras y accesibles de Europa.',
    mejorEpoca: 'Marzo a junio y septiembre a octubre.',
    clima: 'Templado y soleado; inviernos suaves.',
    imperdibles: [
      { titulo: 'Alfama y tranvía 28', texto: 'Callejuelas, miradores y fado.' },
      { titulo: 'Belém', texto: 'La Torre de Belém, el Monasterio de los Jerónimos y los pastéis originales.' },
      { titulo: 'Sintra', texto: 'Palacios de cuento en el bosque, a 40 minutos en tren.' },
    ],
    consejos: ['Lleva zapatos cómodos: hay muchas subidas y calles empedradas.'],
    desdeAeropuerto: 'El aeropuerto está a unos 25 minutos del centro en metro.',
    documento: SCHENGEN, moneda: 'Euro (EUR)', idioma: 'Portugués',
    fotos: { busqueda: 'Lisbon tram Alfama', wikipedia: 'Lisboa' },
  },
  amsterdam: {
    nombre: 'Ámsterdam', region: 'Países Bajos', lema: 'Canales, bicicletas y museos',
    descripcion: 'Casas inclinadas a orillas de los canales, museos de Van Gogh y Rembrandt, y una ciudad que se recorre en bicicleta.',
    mejorEpoca: 'Abril y mayo (tulipanes) y de junio a septiembre.',
    clima: 'Templado y húmedo; inviernos fríos.',
    imperdibles: [
      { titulo: 'Paseo por los canales', texto: 'En barco o a pie por el anillo de canales.' },
      { titulo: 'Museo Van Gogh y Rijksmuseum', texto: 'Reserva tu hora en línea.' },
      { titulo: 'Casa de Ana Frank', texto: 'Las entradas se agotan: cómpralas con anticipación.' },
      { titulo: 'Keukenhof', texto: 'Los jardines de tulipanes más famosos (solo en primavera).' },
    ],
    consejos: ['Respeta las ciclovías: las bicicletas tienen prioridad.'],
    desdeAeropuerto: 'Desde Schiphol a la estación Central hay unos 15–20 minutos en tren.',
    documento: SCHENGEN, moneda: 'Euro (EUR)', idioma: 'Neerlandés (el inglés se habla mucho)',
    fotos: { busqueda: 'Amsterdam canals', wikipedia: 'Ámsterdam' },
  },
  tokio: {
    nombre: 'Tokio', region: 'Japón', lema: 'Tradición milenaria y futuro',
    descripcion: 'Templos centenarios junto a rascacielos de neón, la mejor gastronomía del mundo y una ciudad impecablemente organizada. Un viaje que no se olvida.',
    mejorEpoca: 'Marzo y abril (cerezos en flor) y de octubre a noviembre (hojas de otoño).',
    clima: 'Veranos calurosos y húmedos; inviernos fríos y secos.',
    imperdibles: [
      { titulo: 'Shibuya y Shinjuku', texto: 'El cruce más famoso del mundo y barrios de luces.' },
      { titulo: 'Asakusa y el templo Senso-ji', texto: 'El templo más antiguo de Tokio.' },
      { titulo: 'Monte Fuji', texto: 'Excursión de un día a la zona de los cinco lagos.' },
      { titulo: 'Kioto', texto: 'Templos y geishas, a 2 horas y media en tren bala.' },
    ],
    consejos: [
      'Carga tu tarjeta de transporte (Suica o Pasmo) para metro y trenes.',
      'Evalúa el Japan Rail Pass si vas a viajar a otras ciudades.',
    ],
    desdeAeropuerto: 'Desde Haneda al centro hay unos 30 minutos; desde Narita, aprox. 1 hora en el Narita Express.',
    documento: 'Peruanos: pasaporte y visa japonesa. Tramítala con tiempo en la Embajada del Japón.',
    moneda: 'Yen japonés (JPY)', idioma: 'Japonés',
    fotos: { busqueda: 'Tokyo Japan Shibuya', wikipedia: 'Tokio' },
  },
};
